### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by texnixe** [S1SYPHOS/kirby-lingonberry#12]
@S1SYPHOS: Since you asked, here are a few things :wink:

- What baffles me most is the utter lack of semantic HTML elements, it's divs all over the place.
- Why are there all these empty divs to clear floats? If you really want to stick with floats instead of using flexbox, for example, I'd use a standard clearfix class.
-  jQuery for those few lines of JS?
-  Don't use `user-scalable:no`
- Use svg (sprites) instead of 1x/2y PNGs
- srcset for images where applicable

**Comment by S1SYPHOS** [comment]
Hey there,
great input, thanks! About most of the things in this list, I feel the
same way, but as already mentioned, they are due to

- the original theme being very old (and kind of quirky) and
- me sticking to it very closely.

I'm constantly approaching Lingonberry's creator with bugs, possible
improvements, the likes. I'd be verry happy to see the stuff you
mentioned, which I'm grateful for, in the original, too.

I'll leave this open until I hear back from him or at least until I
decide to 'pork' (port+fork) it :champagne:

Cheers!

**Comment by S1SYPHOS** [comment]
Memo:
- [ ] Vanilla JS
- [ ] SVG (sprites) instead of 1x/2y PNGs
- [ ] Semantic HTML
- [ ] Clearfix class OR flexbox
- [ ] != `user-scalable:no`
- [ ] Srcset for images where applicable
